// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlhjxtkyaosbpcoipmey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsaGp4dGt5YW9zYnBjb2lwbWV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MTM4MzMsImV4cCI6MjA3MjM4OTgzM30.Qgsf3rujeUvyiJH8-0a3mrfO8KLZaQsKSmBabZg9GAM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});